### ISSUE TITLE
修得単位数の表記の改善

### ISSUE THREAD

**Issue by inaniwaudon** [Mimori256/Graduation-Checker#19]
はじめまして、大変便利なツールを提供頂きありがとうございます。

使用時に以下の仕様に気が付きました。

- 「GB, GE 〇」などの部分は、`min(修得単位数, 上限単位数) / 修得すべき単位数` が表示される。
したがって、上限以上の単位数を取っても上限までしか表示されない  
（図中では 13 単位を取得していますが、`9/9` と表示されています）
- その下の「関連科目選択」などの部分は、`修得単位数 / 修得すべき単位数` が表示される

もし意図しないものであれば、表記を `修得単位数 / 修得すべき単位数` に統一した方が混乱を招かないかと思うのですが、いかがでしょうか。ご検討お願いいたします。

<img width="530" alt="image" src="https://user-images.githubusercontent.com/69859801/209102655-871361bb-5f3a-4ab5-b713-a77223d2800d.png">

**Comment by Mimori256** [comment]
![image](https://user-images.githubusercontent.com/80367947/209456555-51dc6a9e-89e4-47b0-b1c0-38a709c45e51.png)
Issueありがとうございます。上のような表記になるように修正しました。
