### ISSUE TITLE
選択科目全体の単位数が上限を突破する

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#29]
![image](https://user-images.githubusercontent.com/49474508/233232593-bb7af889-6ccb-4d4b-92f6-843bf950d541.png)
メディア創成の選択科目上限は74ですが，それに対する上限設定がなされていないようです

**Comment by Mimori256** [comment]
これ、とりあえずとった単位数の合計を表示するために、あえてこの表示にしているのですが、変えたほうがいいですかね
(もちろん単位数が124以上でも、必修とかの条件が満たされていなければ◯にはならない)

**Comment by kzsh4124** [comment]
関連科目とかは上限突破しないようになってるので一貫性を担保するならその方がいいんじゃないかと思いました。(上限突破分は事実上卒業要件としては関係ないわけですし)

**Comment by Mimori256** [comment]
了解です。修正しときます
