### ISSUE TITLE
知識情報・図書館学類-情報資源経営を選択した際実行結果が表示されない

### ISSUE THREAD

**Issue by KeitaW4ra** [Mimori256/Graduation-Checker#56]
知識情報・図書館学類-情報資源経営を選択し、csvファイルを選択してもアプリケーションが実行されず動作しませんでした。
学類を選択するselect要素を使用してからファイルを選択すると実行されないため、select要素周りで何かしらがうまくいっていなさそうだなとは思います。（TSに知見がないので何もわかりませんが...）
実行環境はchromeです。お手すきの際に見てもらえると助かります。

**Comment by Mimori256** [comment]
報告ありがとうございます。確認します。

**Comment by Mimori256** [comment]
#57 で対応しました。
