### ISSUE TITLE
Dでも修得したと判断されるケースがある

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#78]
情報や英語の必修単位が全ては取れていないにもかかわらず、要件を満たしていると判断される場合があるようです。（おそらくDの単位を含む場合？）
再現環境はメディア創成の2022以降の要件ですが、それ以外の確認はしてないので、他の要件を用いた場合や、他のグループでも同様のバグがあるかもしれません。
![image](https://github.com/Mimori256/Graduation-Checker/assets/49474508/1bc6f50b-6446-4a9a-a712-0d7626fb3442)

**Comment by Mimori256** [comment]
こっちでも再現しました。確認します

**Comment by Mimori256** [comment]
#79 で対応できました。
(恐らくこれで大丈夫じゃないかと思います...)
