### ISSUE TITLE
英語の選択科目が必修科目の中に入っている

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#8]
![image](https://user-images.githubusercontent.com/49474508/180198865-8fbdb93e-a4d9-4dc4-90db-584f80a0a9de.png)
見つけたのでissueだけ立てておきます。
本来選択科目に入るべき科目が必修科目としてカウントされるという挙動が確認できました

**Comment by Mimori256** [comment]
bf1a5830edb54c990083e63d2e05993ad8c5c418
修正しました。もし挙動が変わらなければ、ブラウザのキャッシュを削除して再度試してみてください。
