### ISSUE TITLE
klisの必修科目である専門英語BおよびCが反映されない

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#83]
シラバス上ではklisの必修科目は専門英語B、Cですが、実際の科目名は専攻ごとにB|C - ([1-3])に分かれています。
このため、未履修扱いとなってしまいます。

![image](https://github.com/Mimori256/Graduation-Checker/assets/49474508/6760c4bc-9752-4264-aabd-a9b68ea177aa)

![image](https://github.com/Mimori256/Graduation-Checker/assets/49474508/002784a7-f662-41f1-bca8-0bb34a75a3f1)

**Comment by Mimori256** [comment]
@kzsh4124 ちょっと klis 生のデータが手元にないので、確認したいのですが、例として、"専門英語B" を修得している = 専門英語B-1, 専門英語B-2, 専門英語B-3 のいずれかの単位を修得している。という認識であっていますか?

**Comment by kzsh4124** [comment]
その認識です。
そして、3つの中のどれを取るかは専攻によって決まってます。
例えば [専門英語B-1](https://kdb.tsukuba.ac.jp/syllabi/2024/GE50712/jpn) は知識科学主専攻の科目です。なので専攻ごとにjsonの必修部分を変えれば良いと思います。
@Mimori256

**Comment by kzsh4124** [comment]
すいません、間違えて閉じてしまったので再開しました

**Comment by Mimori256** [comment]
#87 で対応しました。
