### ISSUE TITLE
klisの必修科目/選択の科目数が異なる

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#84]
それぞれ50/74となっていますが、おそらくmastのものをそのまま採用していて修正していないのかと思われます。
こちらで確認したところ、　klis21の必修単位数は41単位でした。確認お願いします。
また、現状のklisでは選択科目上限を超えた単位数が表示されており、https://github.com/Mimori256/Graduation-Checker/issues/29 を踏まえればこちらも揃える必要があるかもしれません。

**Comment by Mimori256** [comment]
確認しました。確かに41単位ですね...

**Comment by Mimori256** [comment]
#86 で対応しました。
必修と選択の合計単位に関しても、下限(124単位)を超えた単位数が表示される問題が新しく見つかりましたが、この issue の範囲に該当しないので、別途対応します。
