### ISSUE TITLE
選択科目のカウントに誤りがある

### ISSUE THREAD

**Issue by kzsh4124** [Mimori256/Graduation-Checker#9]
現在、おそらく他学類の科目、GB/GEの科目、博物館に関する科目が独立にカウントされていると思いますが、履修要覧によれば、これらは3つの枠組みをまとめて15単位までしか卒業単位に含むことができないようです。

**Comment by Mimori256** [comment]
e0901a102434ad77d59aa90f0530d7a2cea9513b
修正しました。表記に大きな変更はありませんが、内部の計算の挙動を対応させました
